### PR TITLE
Add features & type declarations

### PR DESCRIPTION
**Pull request by gliese1337**
This also avoids polluting the prototype of `just-a-list`.

### CODE REVIEW

**Comment by gliese1337** [comment]
@ekg 

With the last commit added, this PR now adds support for generators per #3 and arbitrary type support per #2 .

I went to some effort to maintain backwards-compatibility with the existing minimal API. Some simplification could be done if that were given up, but it's not really necessary. All internal operations are now done strictly on integers, so we maintain efficiency, but these are mapped to whatever arbitrary objects were provided as input when a new permutation is outputted. All inputs, including multiset elements that are already integers, are stored in a mapping array that records their original positions as well as their identities; this allows for making guarantees about where in the sequence the outputs will start (it would be ideal if we could guarantee starting at the input permutation, but I haven't figured that out yet; at the moment, it guarantees that the ordering of first appearance of each element is maintained).

I also added several auxiliary functions to handle input in different formats and pre-calculation of the number of permutations that will be produced.

**Comment by gliese1337** [comment]
I also added much more extensive tests, and eliminated the List library dependency, as it became unnecessary.

**Comment by ekg** [comment]
Is this mergable?

**Comment by gliese1337** [comment]
@ekg Yup! No conflicts with the base branch, maintains backwards compatibility, and I incremented the version number so it is immediately publishable.

**Comment by ekg** [comment]
Thank you!

**Pull request merged**
